# Generated by Django 5.1.3 on 2024-12-02 08:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HR',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=100)),
                ('contact', models.IntegerField()),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('transgender', 'Transgender')], max_length=50)),
                ('dob', models.DateField()),
                ('address', models.CharField(max_length=255)),
                ('department', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=100)),
                ('dateOfHired', models.DateField()),
                ('dateOfJoined', models.DateField()),
                ('profilePic', models.ImageField(default='hr/profile-picture.png', upload_to='hr_profile_pics/')),
                ('active', models.BooleanField(default=True)),
                ('user', models.OneToOneField(blank=True, limit_choices_to={'type': 'HR'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hr', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'hr',
            },
        ),
    ]
