# Generated by Django 4.2.16 on 2024-11-27 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminuser',
            name='role',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='password',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='role',
        ),
        migrations.RemoveField(
            model_name='user',
            name='note',
        ),
        migrations.AlterField(
            model_name='employee',
            name='user',
            field=models.OneToOneField(blank=True, limit_choices_to={'type': 'EMPLOYEE'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee', to='accounts.user'),
        ),
    ]
