# Generated by Django 5.1.3 on 2024-12-11 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hr',
            name='profilePic',
            field=models.ImageField(null=True, upload_to='profile_pics/'),
        ),
        migrations.AlterField(
            model_name='manager',
            name='profilePic',
            field=models.ImageField(null=True, upload_to='profile_pics/'),
        ),
    ]
