# Generated by Django 4.2.16 on 2024-11-27 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_adminuser_role_remove_employee_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminuser',
            name='password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
