# Generated by Django 5.1.3 on 2024-12-09 16:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ppa', models.FloatField()),
                ('monthly_salary', models.FloatField()),
                ('basic_da', models.FloatField()),
                ('hra', models.FloatField()),
                ('conveyance', models.FloatField()),
                ('pf', models.FloatField()),
                ('esic', models.FloatField()),
                ('professional_tax', models.FloatField()),
                ('net_salary', models.FloatField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'salary',
            },
        ),
        migrations.CreateModel(
            name='MonthlySalary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('total_salary', models.FloatField()),
                ('paid_amount', models.FloatField(default=0)),
                ('balance_amount', models.FloatField(default=0)),
                ('paid_status', models.BooleanField(default=False)),
                ('paid_date', models.DateField(blank=True, null=True)),
                ('payment_due_date', models.DateField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_salaries', to=settings.AUTH_USER_MODEL)),
                ('salary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_salaries', to='salary.salary')),
            ],
            options={
                'verbose_name': 'Monthly Salary',
                'verbose_name_plural': 'Monthly Salaries',
                'db_table': 'monthly_salary',
            },
        ),
    ]
