# Generated by Django 5.1.3 on 2024-12-09 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='holiday',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='holiday_images/'),
        ),
        migrations.AddField(
            model_name='holiday',
            name='quotes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
